Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "bin/**/*"
    - "config/boot.rb"
    - "db/migrate/20160502181602_devise_create_users.rb"
    - "config/deploy/production.rb"
    - "query_upwork.rb"

Metrics/LineLength:
  Exclude:
    - "db/schema.rb"
    - "config/initializers/devise.rb"
    - "Guardfile"
  Max: 120

Metrics/MethodLength:
  Exclude:
    - "db/migrate/20150706145806_create_job_posts.rb"
  Max: 12

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: true
  Exclude:
    - "app/controllers/*"
    - "app/helpers/*"
    - "db/migrate/*"
    - "config/application.rb"
    - "config/initializers/configuration.rb"

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Exclude:
    - "db/migrate/*"
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Style/NumericLiterals:
  Exclude:
    - "db/schema.rb"

Style/SpaceBeforeFirstArg:
  Exclude:
    - "db/schema.rb"

Style/LeadingCommentSpace:
  Exclude:
    - Gemfile

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - "db/schema.rb"

Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"

Style/DotPosition:
  EnforcedStyle: trailing

Rails/TimeZone:
  Enabled: false

Rails/Output:
  Exclude:
    - "lib/upwork_client_setup.rb"
