language: ruby
cache: bundler
before_install:
  - gem install bundler -v=1.16.2
before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:migrate RAILS_ENV=test
script:
  - bundle exec rspec
