# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  upwork_api:
    consumer_key: <%= ENV["UPWORK_CONSUMER_KEY"] %>
    consumer_secret: <%= ENV["UPWORK_CONSUMER_SECRET"] %>
    access_token: <%= ENV["UPWORK_ACCESS_TOKEN"] %>
    access_secret: <%= ENV["UPWORK_ACCESS_SECRET"] %>

test:
  secret_key_base: eba2f3a08559fc5b712b16de454534589a74658328eb6b04b89e41db05d31af867f84b0ebc2b1e3c74ab35d321fb2339d6995ac20f69aaa41c8c202a6d2b844e5
  upwork_api:
    consumer_key: lala
    consumer_secret: lala
    access_token: lala
    access_secret: lala

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
